const $ = s => document.querySelector(s);
let data, activeList, questions = [], current = 0, set = 1, mastered = 0, direction = 'word', style = 'typing', endless = false, orderedWords = [], nextWord = 0, batchSize = 0;
const show = id => ['loading','study','quiz','done','error'].forEach(x => $(`#${x}`).classList.toggle('hidden', x !== id));
const clean = text => String(text).trim().toLocaleLowerCase();
const escapeHtml = text => String(text).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function shuffle(items) { const copy = [...items]; for (let i = copy.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [copy[i], copy[j]] = [copy[j], copy[i]]; } return copy; }
function renderLists() { $('#listChoices').innerHTML = data.lists.map((list, i) => `<label class="list-choice"><input type="radio" name="list" value="${escapeHtml(list.id)}" ${i ? '' : 'checked'}><strong>${escapeHtml(list.name)}</strong><small>${escapeHtml(list.description || `${list.words.length} words`)}</small></label>`).join(''); }
async function load() { try { const r = await fetch('./data/vocabulary.json', {cache:'no-store'}); if (!r.ok) throw new Error(); data = await r.json(); if (!Array.isArray(data.lists) || !data.lists.length || !Number.isInteger(data.setLength)) throw new Error(); renderLists(); $('#setInfo').textContent = `${data.setLength} questions per set`; show('study'); } catch { show('error'); } }
function beginStudy() { activeList = data.lists.find(x => x.id === document.querySelector('input[name=list]:checked').value); direction = document.querySelector('input[name=direction]:checked').value; style = document.querySelector('input[name=style]:checked').value; endless = document.querySelector('input[name=studyLength]:checked').value === 'endless'; set = 1; orderedWords = [...activeList.words]; nextWord = 0; startSet(); }
function startSet() { if (endless) { questions = shuffle(activeList.words).slice(0, data.setLength); while (questions.length < data.setLength) questions.push(activeList.words[Math.floor(Math.random() * activeList.words.length)]); } else { questions = orderedWords.slice(nextWord, nextWord + data.setLength); batchSize = questions.length; } current = 0; mastered = 0; show('quiz'); draw(); }
function answerFor(question) { return direction === 'word' ? question.word : question.definition; }
function validAnswers(question) { return direction === 'word' ? [question.word] : [question.definition, ...(question.acceptedAnswers || [])]; }
function promptFor(question) { return direction === 'word' ? question.definition : question.word; }
function draw() { const q = questions[current]; const total = endless ? data.setLength : batchSize; $('#progress').textContent = `SET ${set} · ${mastered} OF ${total} MASTERED`; $('#bar').style.width = `${mastered / total * 100}%`; $('#word').textContent = promptFor(q); $('#prompt').textContent = direction === 'word' ? 'Which vocabulary word matches this definition?' : 'What does this vocabulary word mean?'; $('#feedback').classList.add('hidden'); $('#next').classList.add('hidden'); if (style === 'typing') { $('#answer').value = ''; $('#answer').placeholder = direction === 'word' ? 'Type the vocabulary word…' : 'Type the definition…'; $('#answer').disabled = false; $('#answerForm').classList.remove('hidden'); $('#choices').classList.add('hidden'); $('#answer').focus(); } else { $('#answerForm').classList.add('hidden'); const wrongs = shuffle(activeList.words.filter(w => w.id !== q.id)).slice(0, 3).map(answerFor); const options = shuffle([answerFor(q), ...wrongs]); $('#choices').innerHTML = options.map(option => `<button class="choice-button">${escapeHtml(option)}</button>`).join(''); $('#choices').classList.remove('hidden'); $('#choices').querySelectorAll('button').forEach(button => button.onclick = () => grade(button.textContent)); } }
function grade(answer) { const q = questions[current]; const correct = validAnswers(q).map(clean).includes(clean(answer)); if (correct) mastered++; else questions.push(q); $('#answerForm').classList.add('hidden'); $('#choices').classList.add('hidden'); const feedback = $('#feedback'); feedback.className = `feedback ${correct ? '' : 'wrong'}`; feedback.innerHTML = correct ? '<strong>Correct!</strong> Nice work.' : `<strong>Not quite.</strong> The correct answer is: ${escapeHtml(answerFor(q))}<br><small>You will see this word again before the set is complete.</small>`; $('#next').textContent = correct && mastered === (endless ? data.setLength : batchSize) ? 'Finish set' : 'Next word'; $('#next').classList.remove('hidden'); }
function completeSet() { if (!endless) nextWord += batchSize; const finishedList = !endless && nextWord >= orderedWords.length; $('#doneLabel').textContent = finishedList ? 'LIST COMPLETE' : 'SET COMPLETE'; $('#doneTitle').textContent = finishedList ? 'You mastered the list.' : 'Excellent work.'; $('#doneText').textContent = finishedList ? `You answered all ${orderedWords.length} words in ${activeList.name} correctly.` : endless ? 'You completed every word correctly. Ready for a fresh random set?' : `${Math.min(nextWord, orderedWords.length)} of ${orderedWords.length} words completed. Continue in order with the next five words.`; $('#again').textContent = finishedList ? 'Back to home' : endless ? 'Start next random set' : `Start set ${set + 1}`; $('#again').dataset.finished = finishedList ? 'yes' : 'no'; show('done'); }
$('#answerForm').addEventListener('submit', event => { event.preventDefault(); grade($('#answer').value); });
$('#next').onclick = () => { current++; if (current === questions.length) completeSet(); else draw(); };
document.addEventListener('keydown', event => { if (event.key === 'Enter' && !$('#next').classList.contains('hidden')) { event.preventDefault(); $('#next').click(); } });
$('#start').onclick = beginStudy; $('#again').onclick = () => { if ($('#again').dataset.finished === 'yes') show('study'); else { set++; startSet(); } }; load();
